### ISSUE TITLE
baseUrlApi wird nicht verwendet

### ISSUE THREAD

**Issue by Lapotor** [Denncore/jbm-creator-network#24]
Wenn in der app `ng-jbm` in der `src/environments/environment.ts` `baseUrlApi` als `https://api.jbm-creator.network/api` definiert wird dies dennoch nicht für API Calls aus dem Frontend verwendet.

**Comment by Denncore** [comment]
@Lapotor wie genau führst du das aus? Ich habe es eben local und mit dem docker-compose getestet und es wird der wert in der baseUrlApi genommen. Da das backend anscheinend auch schon unter https://api.jbm-creator.network/api öffentlich erreichbar habe ich auch die Daten darüber bekommen.

![image](https://user-images.githubusercontent.com/5949287/213924440-0b3b1625-d727-40ab-9ffa-5528ac6ecab6.png)


Der eigentliche Gedanke hier war das das Backend nicht öffentlich exposed wird sondern nur vom Frontend aus innerhalb der k8s clusters erreichbar ist. Ich sehe es Kritisch wenn das Backend öffentlich ohne auth erreichbar wäre.

**Comment by Lapotor** [comment]
Sehe ich das richtig das es SSR gibt?
Sonst sehe ich aktuell nicht den Weg das Frontend abzukoppeln.

Ich habe die baseApiUri über die `environment.src` im `ng-jbm` oder ist dies eine `process.env` die abgerufen wird.

**Comment by Denncore** [comment]
Ich wüsste jetzt nicht warum SSR dazu notwendig wäre. Das backend von außen abzukoppeln ist eine reine Netzwerk Angelegenheit. Sowohl mit plain Docker networks, vNets oder im Kubernetes cluster kann man das Netzwerk so einstellen das dass backend nur innerhalb des clusters erreichbar ist und nicht von der Außenwelt. 

Ungefähr so: https://kubernetes.io/docs/tasks/access-application-cluster/connecting-frontend-backend/

**Comment by Denncore** [comment]
Bezüglich der environment.src das ist der richtige Platz, dort habe ich es auch getestet. Hast du das Dockerimage komplett neu gebaut nach der Änderung?

**Comment by Lapotor** [comment]
Keine Ahnung wieso aber baseUri funktioniert soweit.

Die API ist bei Client-Side-Rendering schwierig zu verstecken bzw. abzukoppeln, da sonst dein Browser die API nicht mehr ansprechen kann.
